spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service
            uri: lb://auth-service
            predicates:
              - Path=/api/auth/**
          - id: movies-service
            uri: lb://movies-service
            predicates:
              - Path=/api/movies/**, /api/genres/**, /api/reviews/**